import { kanit } from 'src/fonts/font';
import '../../styles/globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={ `${kanit.className} antialiased`}>{children}</body>
    </html>
  )
}
